Repository artsy/exchange, pull requests merged in 2018-10, with the labels that each got.

#208 let me turn on debugging
  config/initializers/datadog.rb
Labels: Merge On Green

#209 wrong env var name
  config/initializers/datadog.rb
Labels: Merge On Green

#223 Add support for searching by code
  app/admin/orders.rb
Labels: Merge On Green

#231 Make postal code optional
  app/models/order.rb
  spec/models/order_spec.rb
Labels: Merge On Green

#234 Make :not_found return 404 instead of 401
  app/controllers/concerns/error_handler.rb
  app/controllers/errors/auth_error.rb
  app/controllers/errors/error_types.rb
  app/graphql/types/query_type.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/controllers/api/requests/orders_query_request_spec.rb
Labels: Jira Synced

#237 Add order id to transaction events
  app/events/transaction_event.rb
  spec/events/transaction_event_spec.rb
Labels: Merge On Green

#235 Upgrade Ruby and bundle update
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: Merge On Green

#254 Update Readme and new danger rule
  README.md
  dangerfile.ts
Labels: Analytics

#262 Remove Order status link from Order details page
  app/admin/orders.rb
  app/helpers/url_helper.rb
Labels: Jira Synced
