Repository artsy/exchange, pull requests merged in 2018-11, with the labels that each got.

#263 Save user agent and ip address at order creation time
  app/controllers/api/graphql_controller.rb
  app/graphql/mutations/create_offer_order_with_artwork.rb
  app/graphql/mutations/create_order_with_artwork.rb
  app/services/base_create_order_service.rb
  app/services/create_buy_order_service.rb
  app/services/create_offer_order_service.rb
  db/migrate/20181030164042_add_order_analytics_fields.rb
  db/schema.rb
  spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
  spec/support/graphlient_client.rb
Labels: Jira Synced

#269 Add order.mode to posted events
  app/events/order_event.rb
  app/events/transaction_event.rb
  spec/events/order_event_spec.rb
  spec/events/transaction_event_spec.rb
Labels: Jira Synced

#271 Accept Offer Mutation
  _schema.graphql
  app/controllers/errors/error_types.rb
  app/graphql/mutations/approve_order.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/confirm_pickup.rb
  app/graphql/mutations/fulfill_at_once.rb
  app/graphql/mutations/initial_offer.rb
  app/graphql/mutations/reject_order.rb
  app/graphql/mutations/seller_accept_offer.rb
  app/graphql/mutations/set_payment.rb
  app/graphql/mutations/set_shipping.rb
  app/graphql/mutations/submit_order.rb
  app/graphql/types/mutation_type.rb
  app/models/offer.rb
  app/services/offers/accept_service.rb
  spec/controllers/api/requests/seller_accept_offer_mutation_request_spec.rb
  spec/models/offer_spec.rb
  spec/services/offers/accept_service_spec.rb
Labels: Jira Synced

#273 Line Item List Price
  _schema.graphql
  app/admin/orders.rb
  app/controllers/errors/error_types.rb
  app/events/order_event.rb
  app/events/transaction_event.rb
  app/graphql/types/line_item_type.rb
  app/graphql/types/order_type.rb
  app/models/line_item.rb
  app/models/order.rb
  app/services/base_create_order_service.rb
  app/services/order_total_updater_service.rb
  app/services/sales_tax_service.rb
  db/migrate/20181105214933_rename_line_item_price_cents.rb
  db/schema.rb
  spec/controllers/api/requests/create_offer_order_with_artwork_mutation_request_spec.rb
  spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
  spec/controllers/api/requests/fulfill_at_once_request_spec.rb
  spec/controllers/api/requests/initial_offer_mutation_request_spec.rb
  spec/controllers/api/requests/order_field_permissions_spec.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/events/order_event_spec.rb
  spec/events/transaction_event_spec.rb
  spec/fabricators/line_item_fabricator.rb
  spec/models/line_item_spec.rb
  spec/models/order_line_item_spec.rb
  spec/services/create_buy_order_service_spec.rb
  spec/services/create_offer_order_service_spec.rb
  spec/services/offers/initial_offer_service_spec.rb
  spec/services/order_approve_service_spec.rb
  spec/services/order_cancellation_service_spec.rb
  spec/services/order_service_spec.rb
  spec/services/order_submit_service_spec.rb
  spec/services/order_total_updater_service_spec.rb
  spec/services/sales_tax_service_spec.rb
Labels: Jira Synced

#281 Add mutation for submitting an offer-type order
  .rubocop.yml
  _schema.graphql
  app/controllers/errors/error_types.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/submit_order_with_offer.rb
  app/graphql/types/mutation_type.rb
  app/models/offer.rb
  app/models/order.rb
  app/services/offers/submit_order_service.rb
  app/services/order_submit_service.rb
  spec/controllers/api/requests/submit_order_with_offer_mutation_request_spec.rb
  spec/services/offers/submit_order_service_spec.rb
Labels: Jira Synced

#280 Remove ability for sales admins to access orders via GraphQL
  app/graphql/types/query_type.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/controllers/api/requests/orders_query_request_spec.rb
Labels: Jira Synced

#276 Verify that credit given in set payment step belongs to buyer
  app/controllers/errors/error_types.rb
  app/services/order_service.rb
  spec/controllers/api/requests/set_payment_mutation_request_spec.rb
  spec/services/order_service_spec.rb
Labels: Jira Synced

#282 Filter out pending offers in order.offers
  _schema.graphql
  app/graphql/types/order_type.rb
  app/models/offer.rb
  spec/controllers/api/requests/initial_offer_mutation_request_spec.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/models/offer_spec.rb
Labels: Jira Synced

#285 Update rack
  Gemfile.lock
Labels: Merge On Green

#294 Sellers provide offer rejection reason
  _schema.graphql
  app/controllers/errors/error_types.rb
  app/graphql/mutations/seller_reject_offer.rb
  app/graphql/types/cancel_reason_type_enum.rb
  app/models/order.rb
  app/services/offers/accept_service.rb
  app/services/offers/base_offer_service.rb
  app/services/offers/reject_offer_service.rb
  spec/controllers/api/requests/seller_reject_offer_mutation_request_spec.rb
  spec/events/order_event_spec.rb
  spec/services/offers/accept_service_spec.rb
  spec/services/offers/reject_offer_service_spec.rb
  spec/services/order_cancellation_service_spec.rb
Labels: Jira Synced

#301 Add from_participant to Offer and expose it in OfferType
  _schema.graphql
  app/graphql/types/offer_order_type.rb
  app/graphql/types/offer_type.rb
  app/graphql/types/order_participant_enum.rb
  app/models/offer.rb
  app/models/order.rb
  spec/controllers/api/requests/order_my_offer_request_spec.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/models/offer_spec.rb
Labels: Jira Synced

#297 Add `buyerTotalCents` to `OfferType`
  _schema.graphql
  app/graphql/types/offer_type.rb
  spec/controllers/api/requests/add_initial_offer_to_order_mutation_request_spec.rb
  spec/controllers/api/requests/offer_set_shipping_mutation_request_spec.rb
Labels: Jira Synced, Merge On Green

#295 Notify when offer is approved
  app/events/order_event.rb
  app/events/transaction_event.rb
  app/graphql/mutations/approve_order.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/seller_accept_offer.rb
  app/jobs/post_order_notification_job.rb
  app/services/offers/accept_service.rb
  app/services/offers/submit_order_service.rb
  app/services/order_approve_service.rb
  app/services/order_cancellation_service.rb
  app/services/order_service.rb
  app/services/order_submit_service.rb
  spec/controllers/api/requests/approve_order_mutation_request_spec.rb
  spec/controllers/api/requests/confirm_pickup_request_spec.rb
  spec/events/order_event_spec.rb
  spec/events/transaction_event_spec.rb
  spec/jobs/post_notification_job_spec.rb
  spec/services/offers/accept_service_spec.rb
  spec/services/offers/submit_order_service_spec.rb
  spec/services/order_approve_service_spec.rb
  spec/services/order_cancellation_service_spec.rb
  spec/services/order_service_spec.rb
  spec/services/order_submit_service_spec.rb
Labels: Jira Synced
