Repository artsy/exchange, pull requests merged in 2018-08, with the labels that each got.

#97 Fix csrf issue
  app/controllers/api/base_api_controller.rb
Labels: Merge On Green

#93 Move to the new mutation style
  .vscode/extensions.json
  .vscode/settings.json
  app/graphql/mutations/create_order_with_artwork.rb
  app/graphql/mutations/order_or_failure_union_type.rb
  app/graphql/mutations/plain_mutation.rb
  app/graphql/types/mutation_error_type.rb
  dangerfile.ts
  spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
Labels: Breaking Change

#119 Refactor shipping related Mutations and Type
  README.md
  app/graphql/inputs/fulfillment_attributes.rb
  app/graphql/inputs/shipping_attributes.rb
  app/graphql/mutations/fulfill_at_once.rb
  app/graphql/mutations/set_shipping.rb
  app/graphql/types/fulfillment_union_type.rb
  app/graphql/types/order_type.rb
  app/services/order_service.rb
  spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
Labels: Breaking Change

#121 Rename Partner -> Seller , User -> Buyer
  app/admin/orders.rb
  app/events/order_event.rb
  app/graphql/mutations/approve_order.rb
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/fulfill_at_once.rb
  app/graphql/mutations/reject_order.rb
  app/graphql/mutations/set_payment.rb
  app/graphql/mutations/set_shipping.rb
  app/graphql/mutations/submit_order.rb
  app/graphql/types/base_field.rb
  app/graphql/types/buyer_type.rb
  app/graphql/types/order_party_union_type.rb
  app/graphql/types/order_type.rb
  app/graphql/types/query_type.rb
  app/models/order.rb
  app/services/create_order_service.rb
  app/services/order_submit_service.rb
  app/services/sales_tax_service.rb
  db/migrate/20180822200144_add_buyer_type_to_order.rb
  db/schema.rb
  spec/controllers/api/requests/approve_order_mutation_request_spec.rb
  spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
  spec/controllers/api/requests/fulfill_at_once_request_spec.rb
  spec/controllers/api/requests/order_field_permissions_spec.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/controllers/api/requests/orders_query_request_spec.rb
  spec/controllers/api/requests/reject_order_mutation_request_spec.rb
  spec/controllers/api/requests/set_payment_mutation_request_spec.rb
  spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/events/order_event_spec.rb
  spec/fabricators/order_fabricator.rb
  spec/jobs/post_notification_job_spec.rb
  spec/services/create_order_service_spec.rb
  spec/services/order_submit_service_spec.rb
  spec/services/sales_tax_service_spec.rb
Labels: Breaking Change, MP PR NEEDED

#128 Use new mutation style for submit_order
  README.md
  app/graphql/mutations/submit_order.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
Labels: Breaking Change

#133 Follow new style mutations for rest of mutations
  app/graphql/mutations/approve_order.rb
  app/graphql/mutations/fulfill_at_once.rb
  app/graphql/mutations/reject_order.rb
  app/graphql/mutations/set_payment.rb
  app/graphql/mutations/set_shipping.rb
  spec/controllers/api/requests/approve_order_mutation_request_spec.rb
  spec/controllers/api/requests/fulfill_at_once_request_spec.rb
  spec/controllers/api/requests/reject_order_mutation_request_spec.rb
  spec/controllers/api/requests/set_payment_mutation_request_spec.rb
  spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
Labels: Breaking Change
