Repository artsy/exchange, pull requests merged in 2019-07, with the labels that each got.

#424 PURCHASE-1118 - Finishes steps for exchange hokusai updates
  Dockerfile
  config/puma.config
  config/puma.rb
  hokusai/build.yml
  hokusai/config.yml
  hokusai/development.yml
  hokusai/production.yml
  hokusai/staging.yml
  hokusai/test.yml
Labels: Jira Synced

#430 [PURCHASE-1180] Extend approval expiration to 3 days
  app/models/order.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/events/offer_event_spec.rb
  spec/events/order_event_spec.rb
Labels: Jira Synced

#433 [Deploy] Extend approval time to 72hrs
  .circleci/config.yml
  .rubocop
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  README.md
  _schema.graphql
  app/assets/javascripts/active_admin.js
  app/assets/javascripts/active_admin.js.coffee
  app/assets/stylesheets/active_admin.scss
  app/graphql/mutations/add_initial_offer_to_order.rb
  app/models/fulfillment.rb
  app/models/line_item.rb
  app/models/offer.rb
  app/models/order.rb
  app/models/paper_trail/version.rb
  app/models/transaction.rb
  config/initializers/datadog_statsd.rb
  spec/controllers/api/requests/create_order_with_artwork_mutation_request_spec.rb
  spec/controllers/api/requests/offers/add_initial_offer_to_order_mutation_request_spec.rb
  spec/controllers/api/requests/offers/create_offer_order_with_artwork_mutation_request_spec.rb
  spec/controllers/api/requests/offers/offer_set_shipping_mutation_request_spec.rb
  spec/controllers/api/requests/offers/submit_order_with_offer_mutation_request_spec.rb
  spec/controllers/api/requests/set_shipping_mutation_request_spec.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/events/offer_event_spec.rb
  spec/events/order_event_spec.rb
Labels: Jira Synced

#436 Make GBP a Supported Currency for Orders (GALL-1966)
  app/models/order.rb
  spec/integration/gbp/buy_now_happy_path_spec.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/integration/gbp/reset_shipping_request_spec.rb
  spec/integration/gbp/single_counteroffer_happy_path_spec.rb
  spec/models/order_spec.rb
  spec/support/use_stripe_mock_gbp.rb
Labels: Jira Synced

#444 [Deploy] GBP support + refactor
  .circleci/config.yml
  .rubocop.yml
  app/controllers/errors/insufficient_inventory_error.rb
  app/events/transaction_event.rb
  app/jobs/post_transaction_notification_job.rb
  app/models/order.rb
  app/services/offer_service.rb
  app/services/order_service.rb
  lib/gravity.rb
  lib/order_processor.rb
  spec/controllers/api/requests/line_items_query_request_spec.rb
  spec/events/transaction_event_spec.rb
  spec/integration/gbp/buy_now_happy_path_spec.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/integration/gbp/reset_shipping_request_spec.rb
  spec/integration/gbp/single_counteroffer_happy_path_spec.rb
  spec/jobs/post_transaction_notification_job_spec.rb
  spec/lib/order_processor_spec.rb
  spec/models/order_spec.rb
  spec/support/use_stripe_mock_gbp.rb
Labels: Jira Synced

#443 Switch to payment intent stuff
  app/controllers/errors/error_types.rb
  app/models/transaction.rb
  app/services/order_approve_service.rb
  app/services/order_cancellation_service.rb
  config/initializers/stripe.rb
  db/migrate/20190723204933_add_external_type_and_payload_to_transactions.rb
  db/migrate/20190723204947_populate_transaction_external_type.rb
  db/schema.rb
  lib/order_processor.rb
  lib/payment_service.rb
  spec/controllers/api/requests/approve_order_mutation_request_spec.rb
  spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb
  spec/controllers/api/requests/line_items_query_request_spec.rb
  spec/controllers/api/requests/offers/buyer_accept_offer_mutation_request_spec.rb
  spec/controllers/api/requests/offers/buyer_counter_offer_mutation_request_spec.rb
  spec/controllers/api/requests/offers/reject_offer_mutation_request_spec.rb
  spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb
  spec/controllers/api/requests/offers/seller_counter_offer_mutation_request_spec.rb
  spec/controllers/api/requests/reject_order_mutation_request_spec.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/integration/buy_now_happy_path_spec.rb
  spec/integration/make_offer_happy_path_spec.rb
  spec/integration/single_counteroffer_happy_path_spec.rb
  spec/lib/order_processor_spec.rb
  spec/services/order_approve_service_spec.rb
  spec/services/order_cancellation_service_spec.rb
  spec/services/payment_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced, Merge On Green

#447 Fix GBP tests after merging payment_intent PR
  spec/integration/gbp/buy_now_happy_path_spec.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/integration/gbp/single_counteroffer_happy_path_spec.rb
  spec/support/use_stripe_mock_gbp.rb
Labels: Merge On Green

#448 Fix Failed Payment Intent Issue
  .rubocop.yml
  lib/payment_service.rb
  spec/services/order_approve_service_spec.rb
  spec/services/payment_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Merge On Green

#449 Fix data migration to actually use prefix
  db/migrate/20190723204947_populate_transaction_external_type.rb
Labels: Merge On Green

#453 Add internalID to all our types
  _schema.graphql
  app/graphql/types/fulfillment_type.rb
  app/graphql/types/line_item_type.rb
  app/graphql/types/offer_type.rb
  app/graphql/types/order_interface.rb
  spec/controllers/api/requests/order_query_request_spec.rb
Labels: Jira Synced, Merge On Green

#456 Expose currency_code in offer graphQL response
  _schema.graphql
  app/graphql/types/offer_type.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/support/offer_query_helper.rb
Labels: Merge On Green

#455 Add support for `requires_action` payment_intent state
  .rubocop.yml
  _schema.graphql
  app/controllers/errors/error_types.rb
  app/controllers/errors/payment_requires_action_error.rb
  app/graphql/mutations/order_or_failure_union_type.rb
  app/graphql/mutations/submit_order.rb
  app/graphql/types/order_action_data_type.rb
  app/models/transaction.rb
  app/services/order_service.rb
  hokusai/sca.yml
  lib/order_processor.rb
  lib/payment_service.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/lib/order_processor_spec.rb
  spec/services/payment_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Merge On Green
