Repository artsy/exchange, pull requests merged in 2019-06, with the labels that each got.

#414 #FF Add clc_assisted to Orders and to admin
  app/admin/orders.rb
  db/migrate/20190530201701_add_clc_assisted_to_order.rb
  db/schema.rb
Labels: Jira Synced, Merge On Green

#416 PURCHASE-1137: Fix storing source instead of source.id in transaction.source_id
  lib/payment_service.rb
  spec/services/payment_service_spec.rb
Labels: Jira Synced

#423 PURCHASE-1138: Adds spec for the single counteroffer happy path scenario
  spec/integration/single_counteroffer_happy_path_spec.rb
  spec/support/offer_query_helper.rb
Labels: Merge On Green

#425 Deploy
  spec/integration/single_counteroffer_happy_path_spec.rb
  spec/support/offer_query_helper.rb
Labels: Jira Synced
