Repository artsy/exchange, pull requests merged in 2019-08, with the labels that each got.

#461 Confirm payment intent
  app/controllers/errors/error_types.rb
  app/models/transaction.rb
  lib/order_processor.rb
  lib/payment_service.rb
  spec/integration/buy_now_sca_path.rb
  spec/services/payment_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Merge On Green

#464 clear external_charge_id when updating payment_method
  app/graphql/types/mutation_type.rb
  app/services/order_service.rb
  spec/controllers/api/requests/set_payment_mutation_request_spec.rb
Labels: Jira Synced

#463 Cancel payment intent instead of refund when un-captured
  .rubocop.yml
  app/models/transaction.rb
  app/services/order_cancellation_service.rb
  lib/payment_service.rb
  spec/controllers/api/requests/reject_order_mutation_request_spec.rb
  spec/services/order_cancellation_service_spec.rb
  spec/support/offer_query_helper.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced

#465 Fix passing empty hash
  lib/payment_service.rb
Labels: Merge On Green

#466 #FF Add external_id and type to transaction events
  app/events/transaction_event.rb
  spec/events/transaction_event_spec.rb
Labels: Merge On Green

#468 [Deploy] Full switch to payment intent for BN + proper cancelation
  .rubocop.yml
  .rubocop_todo.yml
  _schema.graphql
  app/controllers/errors/error_types.rb
  app/controllers/errors/payment_requires_action_error.rb
  app/events/transaction_event.rb
  app/graphql/mutations/order_or_failure_union_type.rb
  app/graphql/mutations/submit_order.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/order_action_data_type.rb
  app/models/transaction.rb
  app/services/order_cancellation_service.rb
  app/services/order_service.rb
  hokusai/sca.yml
  lib/order_processor.rb
  lib/payment_service.rb
  spec/controllers/api/requests/reject_order_mutation_request_spec.rb
  spec/controllers/api/requests/set_payment_mutation_request_spec.rb
  spec/controllers/api/requests/submit_order_mutation_request_spec.rb
  spec/events/transaction_event_spec.rb
  spec/integration/buy_now_sca_path.rb
  spec/lib/order_processor_spec.rb
  spec/services/order_cancellation_service_spec.rb
  spec/services/payment_service_spec.rb
  spec/support/offer_query_helper.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced

#469 Fixed checking for wrong payment intent state after SCA
  lib/payment_service.rb
  spec/support/stripe_helper.rb
Labels: Merge On Green

#470 Add new mode to charge metadata + undeduct in case of other errors
  lib/order_processor.rb
  spec/lib/order_processor_spec.rb
Labels: Jira Synced

#473 Add statsd for require action
  .rubocop.yml
  app/services/order_service.rb
Labels: Merge On Green

#474 [Deploy] Sales Tax + new charge metadata + statsd
  .circleci/config.yml
  .rubocop.yml
  app/services/order_service.rb
  lib/order_processor.rb
  lib/tax/calculator_service.rb
  spec/integration/gbp/buy_now_happy_path_spec.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/lib/order_processor_spec.rb
Labels: Jira Synced

#477 Add service for setup intent processing on offer submission
  app/graphql/mutations/submit_order_with_offer.rb
  app/models/transaction.rb
  app/services/offer_service.rb
  lib/offer_processor.rb
  lib/order_processor.rb
  lib/payment_method_service.rb
  spec/controllers/api/requests/offers/submit_order_with_offer_mutation_request_spec.rb
  spec/integration/gbp/make_offer_happy_path_spec.rb
  spec/integration/gbp/single_counteroffer_happy_path_spec.rb
  spec/integration/make_offer_happy_path_spec.rb
  spec/integration/single_counteroffer_happy_path_spec.rb
  spec/lib/offer_processor_spec.rb
  spec/lib/payment_method_service_spec.rb
  spec/lib/payment_service_spec.rb
  spec/services/offer_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced

#481 Fix test broke because of famous copy/paste
  spec/integration/make_offer_sca_happy_path_spec.rb
Labels: Merge On Green

#484 PURCHASE-1445: Only setup future usage for on-session PaymentIntents
  .rubocop.yml
  lib/payment_service.rb
  spec/lib/payment_service_spec.rb
Labels: Jira Synced, Merge On Green

#486 PURCHASE-1428: Get failed payment flow working with case where payment intent of a already confirmed setupintent fails when seller accepts offer
  app/services/offer_service.rb
  spec/controllers/api/requests/offers/seller_accept_offer_mutation_request_spec.rb
  spec/services/offer_service_spec.rb
Labels: Jira Synced

#489 PURCHASE-1428: Get failed payment flow working with case where payment intent of a already confirmed setupintent fails when seller accepts offer
  app/graphql/mutations/fix_failed_payment.rb
  spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb
Labels: Jira Synced, Merge On Green

#488 Reuse Confirmed SteupIntent
  _schema.graphql
  app/graphql/mutations/submit_order_with_offer.rb
  app/services/offer_service.rb
  lib/offer_processor.rb
  lib/payment_method_service.rb
  spec/lib/offer_processor_spec.rb
  spec/lib/payment_method_service_spec.rb
  spec/services/offer_service_spec.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced

#491 Fix failed payment with required action
  app/models/order.rb
  spec/controllers/api/requests/fix_failed_payment_mutation_request_spec.rb
Labels: Jira Synced
