Repository artsy/exchange, pull requests merged in 2019-09, with the labels that each got.

#492 Reuse payment intent on resubmitting during failed payment flow
  .rubocop.yml
  app/graphql/mutations/fix_failed_payment.rb
  app/services/offer_service.rb
  lib/order_processor.rb
  spec/integration/fix_failed_payment_flow_with_sca_card.rb
  spec/lib/order_processor_spec.rb
  spec/services/offer_service_spec.rb
  spec/support/offer_query_helper.rb
  spec/support/stripe_helper.rb
Labels: Merge On Green

#494 PURCHASE-1474: Wrong expiration on offers with failed payment flow
  lib/order_processor.rb
  spec/integration/fix_failed_payment_flow_with_sca_card.rb
  spec/lib/order_processor_spec.rb
Labels: Jira Synced, Merge On Green

#495 [Deploy] Fix issue with not expiring orders
  app/admin/orders.rb
  app/helpers/admin_helper.rb
  lib/order_processor.rb
  spec/integration/fix_failed_payment_flow_with_sca_card.rb
  spec/lib/order_processor_spec.rb
Labels: Jira Synced

#496 Fix issue with offer page in admin
  app/admin/orders.rb
Labels: Merge On Green

#498 GALL-2120: Relax admin check
  app/graphql/types/query_type.rb
  lib/artsy_auth_token.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/controllers/api/requests/orders_query_request_spec.rb
Labels: Merge On Green

#499 Introduce new other payment method
  app/models/order.rb
Labels: Merge On Green

#500 [Deploy] Relax Admin Check + Other Payment method
  app/graphql/types/query_type.rb
  app/models/order.rb
  lib/artsy_auth_token.rb
  spec/controllers/api/requests/order_query_request_spec.rb
  spec/controllers/api/requests/orders_query_request_spec.rb
Labels: Jira Synced

#504 Fix issue with admin auth
  app/graphql/types/query_type.rb
  lib/artsy_auth_token.rb
Labels: Merge On Green

#508 Fix issue where SetupIntent.create could raise error and we were not …
  app/controllers/errors/error_types.rb
  lib/offer_processor.rb
  lib/payment_method_service.rb
  spec/controllers/api/requests/offers/submit_order_with_offer_mutation_request_spec.rb
  spec/lib/offer_processor_spec.rb
  spec/support/stripe_helper.rb
Labels: Jira Synced
